# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attr_view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(440, 410)
        self.btn_ok = QtGui.QPushButton(Form)
        self.btn_ok.setGeometry(QtCore.QRect(170, 370, 110, 32))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_21.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(44, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_21.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_21.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(53, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(-10, 40, 451, 312))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 434, 1064))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.field_nm_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_1.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_1.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_1.setFont(font)
        self.field_nm_1.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_1.setObjectName(_fromUtf8("field_nm_1"))
        self.horizontalLayout.addWidget(self.field_nm_1)
        self.edt_before_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_1.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_1.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_1.setReadOnly(True)
        self.edt_before_1.setObjectName(_fromUtf8("edt_before_1"))
        self.horizontalLayout.addWidget(self.edt_before_1)
        self.edi_after_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_1.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_1.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_1.setReadOnly(True)
        self.edi_after_1.setObjectName(_fromUtf8("edi_after_1"))
        self.horizontalLayout.addWidget(self.edi_after_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.field_nm_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_2.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_2.setFont(font)
        self.field_nm_2.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_2.setObjectName(_fromUtf8("field_nm_2"))
        self.horizontalLayout_2.addWidget(self.field_nm_2)
        self.edt_before_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_2.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_2.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_2.setReadOnly(True)
        self.edt_before_2.setObjectName(_fromUtf8("edt_before_2"))
        self.horizontalLayout_2.addWidget(self.edt_before_2)
        self.edi_after_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_2.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_2.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_2.setReadOnly(True)
        self.edi_after_2.setObjectName(_fromUtf8("edi_after_2"))
        self.horizontalLayout_2.addWidget(self.edi_after_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.field_nm_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_3.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_3.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_3.setFont(font)
        self.field_nm_3.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_3.setObjectName(_fromUtf8("field_nm_3"))
        self.horizontalLayout_3.addWidget(self.field_nm_3)
        self.edt_before_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_3.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_3.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_3.setReadOnly(True)
        self.edt_before_3.setObjectName(_fromUtf8("edt_before_3"))
        self.horizontalLayout_3.addWidget(self.edt_before_3)
        self.edi_after_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_3.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_3.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_3.setReadOnly(True)
        self.edi_after_3.setObjectName(_fromUtf8("edi_after_3"))
        self.horizontalLayout_3.addWidget(self.edi_after_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.field_nm_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_4.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_4.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_4.setFont(font)
        self.field_nm_4.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_4.setObjectName(_fromUtf8("field_nm_4"))
        self.horizontalLayout_4.addWidget(self.field_nm_4)
        self.edt_before_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_4.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_4.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_4.setReadOnly(True)
        self.edt_before_4.setObjectName(_fromUtf8("edt_before_4"))
        self.horizontalLayout_4.addWidget(self.edt_before_4)
        self.edi_after_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_4.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_4.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_4.setReadOnly(True)
        self.edi_after_4.setObjectName(_fromUtf8("edi_after_4"))
        self.horizontalLayout_4.addWidget(self.edi_after_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.field_nm_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_5.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_5.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_5.setFont(font)
        self.field_nm_5.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_5.setObjectName(_fromUtf8("field_nm_5"))
        self.horizontalLayout_5.addWidget(self.field_nm_5)
        self.edt_before_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_5.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_5.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_5.setReadOnly(True)
        self.edt_before_5.setObjectName(_fromUtf8("edt_before_5"))
        self.horizontalLayout_5.addWidget(self.edt_before_5)
        self.edi_after_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_5.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_5.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_5.setReadOnly(True)
        self.edi_after_5.setObjectName(_fromUtf8("edi_after_5"))
        self.horizontalLayout_5.addWidget(self.edi_after_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.field_nm_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_6.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_6.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_6.setFont(font)
        self.field_nm_6.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_6.setObjectName(_fromUtf8("field_nm_6"))
        self.horizontalLayout_6.addWidget(self.field_nm_6)
        self.edt_before_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_6.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_6.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_6.setReadOnly(True)
        self.edt_before_6.setObjectName(_fromUtf8("edt_before_6"))
        self.horizontalLayout_6.addWidget(self.edt_before_6)
        self.edi_after_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_6.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_6.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_6.setReadOnly(True)
        self.edi_after_6.setObjectName(_fromUtf8("edi_after_6"))
        self.horizontalLayout_6.addWidget(self.edi_after_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.field_nm_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_7.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_7.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_7.setFont(font)
        self.field_nm_7.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_7.setObjectName(_fromUtf8("field_nm_7"))
        self.horizontalLayout_7.addWidget(self.field_nm_7)
        self.edt_before_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_7.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_7.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_7.setReadOnly(True)
        self.edt_before_7.setObjectName(_fromUtf8("edt_before_7"))
        self.horizontalLayout_7.addWidget(self.edt_before_7)
        self.edi_after_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_7.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_7.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_7.setReadOnly(True)
        self.edi_after_7.setObjectName(_fromUtf8("edi_after_7"))
        self.horizontalLayout_7.addWidget(self.edi_after_7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.field_nm_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_8.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_8.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_8.setFont(font)
        self.field_nm_8.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_8.setObjectName(_fromUtf8("field_nm_8"))
        self.horizontalLayout_8.addWidget(self.field_nm_8)
        self.edt_before_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_8.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_8.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_8.setReadOnly(True)
        self.edt_before_8.setObjectName(_fromUtf8("edt_before_8"))
        self.horizontalLayout_8.addWidget(self.edt_before_8)
        self.edi_after_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_8.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_8.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_8.setReadOnly(True)
        self.edi_after_8.setObjectName(_fromUtf8("edi_after_8"))
        self.horizontalLayout_8.addWidget(self.edi_after_8)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.field_nm_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_9.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_9.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_9.setFont(font)
        self.field_nm_9.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_9.setObjectName(_fromUtf8("field_nm_9"))
        self.horizontalLayout_9.addWidget(self.field_nm_9)
        self.edt_before_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_9.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_9.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_9.setReadOnly(True)
        self.edt_before_9.setObjectName(_fromUtf8("edt_before_9"))
        self.horizontalLayout_9.addWidget(self.edt_before_9)
        self.edi_after_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_9.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_9.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_9.setReadOnly(True)
        self.edi_after_9.setObjectName(_fromUtf8("edi_after_9"))
        self.horizontalLayout_9.addWidget(self.edi_after_9)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.field_nm_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_10.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_10.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_10.setFont(font)
        self.field_nm_10.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_10.setObjectName(_fromUtf8("field_nm_10"))
        self.horizontalLayout_10.addWidget(self.field_nm_10)
        self.edt_before_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_10.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_10.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_10.setReadOnly(True)
        self.edt_before_10.setObjectName(_fromUtf8("edt_before_10"))
        self.horizontalLayout_10.addWidget(self.edt_before_10)
        self.edi_after_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_10.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_10.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_10.setReadOnly(True)
        self.edi_after_10.setObjectName(_fromUtf8("edi_after_10"))
        self.horizontalLayout_10.addWidget(self.edi_after_10)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.field_nm_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_11.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_11.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_11.setFont(font)
        self.field_nm_11.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_11.setObjectName(_fromUtf8("field_nm_11"))
        self.horizontalLayout_11.addWidget(self.field_nm_11)
        self.edt_before_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_11.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_11.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_11.setReadOnly(True)
        self.edt_before_11.setObjectName(_fromUtf8("edt_before_11"))
        self.horizontalLayout_11.addWidget(self.edt_before_11)
        self.edi_after_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_11.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_11.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_11.setReadOnly(True)
        self.edi_after_11.setObjectName(_fromUtf8("edi_after_11"))
        self.horizontalLayout_11.addWidget(self.edi_after_11)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.field_nm_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_12.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_12.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_12.setFont(font)
        self.field_nm_12.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_12.setObjectName(_fromUtf8("field_nm_12"))
        self.horizontalLayout_12.addWidget(self.field_nm_12)
        self.edt_before_12 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_12.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_12.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_12.setReadOnly(True)
        self.edt_before_12.setObjectName(_fromUtf8("edt_before_12"))
        self.horizontalLayout_12.addWidget(self.edt_before_12)
        self.edi_after_12 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_12.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_12.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_12.setReadOnly(True)
        self.edi_after_12.setObjectName(_fromUtf8("edi_after_12"))
        self.horizontalLayout_12.addWidget(self.edi_after_12)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.field_nm_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_13.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_13.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_13.setFont(font)
        self.field_nm_13.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_13.setObjectName(_fromUtf8("field_nm_13"))
        self.horizontalLayout_13.addWidget(self.field_nm_13)
        self.edt_before_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_13.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_13.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_13.setReadOnly(True)
        self.edt_before_13.setObjectName(_fromUtf8("edt_before_13"))
        self.horizontalLayout_13.addWidget(self.edt_before_13)
        self.edi_after_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_13.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_13.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_13.setReadOnly(True)
        self.edi_after_13.setObjectName(_fromUtf8("edi_after_13"))
        self.horizontalLayout_13.addWidget(self.edi_after_13)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.field_nm_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_14.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_14.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_14.setFont(font)
        self.field_nm_14.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_14.setObjectName(_fromUtf8("field_nm_14"))
        self.horizontalLayout_14.addWidget(self.field_nm_14)
        self.edt_before_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_14.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_14.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_14.setReadOnly(True)
        self.edt_before_14.setObjectName(_fromUtf8("edt_before_14"))
        self.horizontalLayout_14.addWidget(self.edt_before_14)
        self.edi_after_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_14.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_14.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_14.setReadOnly(True)
        self.edi_after_14.setObjectName(_fromUtf8("edi_after_14"))
        self.horizontalLayout_14.addWidget(self.edi_after_14)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.field_nm_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_15.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_15.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_15.setFont(font)
        self.field_nm_15.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_15.setObjectName(_fromUtf8("field_nm_15"))
        self.horizontalLayout_15.addWidget(self.field_nm_15)
        self.edt_before_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_15.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_15.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_15.setReadOnly(True)
        self.edt_before_15.setObjectName(_fromUtf8("edt_before_15"))
        self.horizontalLayout_15.addWidget(self.edt_before_15)
        self.edi_after_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_15.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_15.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_15.setReadOnly(True)
        self.edi_after_15.setObjectName(_fromUtf8("edi_after_15"))
        self.horizontalLayout_15.addWidget(self.edi_after_15)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.field_nm_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_16.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_16.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_16.setFont(font)
        self.field_nm_16.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_16.setObjectName(_fromUtf8("field_nm_16"))
        self.horizontalLayout_16.addWidget(self.field_nm_16)
        self.edt_before_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_16.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_16.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_16.setReadOnly(True)
        self.edt_before_16.setObjectName(_fromUtf8("edt_before_16"))
        self.horizontalLayout_16.addWidget(self.edt_before_16)
        self.edi_after_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_16.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_16.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_16.setReadOnly(True)
        self.edi_after_16.setObjectName(_fromUtf8("edi_after_16"))
        self.horizontalLayout_16.addWidget(self.edi_after_16)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.field_nm_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_17.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_17.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_17.setFont(font)
        self.field_nm_17.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_17.setObjectName(_fromUtf8("field_nm_17"))
        self.horizontalLayout_17.addWidget(self.field_nm_17)
        self.edt_before_17 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_17.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_17.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_17.setReadOnly(True)
        self.edt_before_17.setObjectName(_fromUtf8("edt_before_17"))
        self.horizontalLayout_17.addWidget(self.edt_before_17)
        self.edi_after_17 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_17.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_17.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_17.setReadOnly(True)
        self.edi_after_17.setObjectName(_fromUtf8("edi_after_17"))
        self.horizontalLayout_17.addWidget(self.edi_after_17)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.field_nm_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_18.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_18.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_18.setFont(font)
        self.field_nm_18.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_18.setObjectName(_fromUtf8("field_nm_18"))
        self.horizontalLayout_18.addWidget(self.field_nm_18)
        self.edt_before_18 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_18.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_18.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_18.setReadOnly(True)
        self.edt_before_18.setObjectName(_fromUtf8("edt_before_18"))
        self.horizontalLayout_18.addWidget(self.edt_before_18)
        self.edi_after_18 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_18.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_18.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_18.setReadOnly(True)
        self.edi_after_18.setObjectName(_fromUtf8("edi_after_18"))
        self.horizontalLayout_18.addWidget(self.edi_after_18)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.field_nm_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_19.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_19.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_19.setFont(font)
        self.field_nm_19.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_19.setObjectName(_fromUtf8("field_nm_19"))
        self.horizontalLayout_19.addWidget(self.field_nm_19)
        self.edt_before_19 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_19.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_19.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_19.setReadOnly(True)
        self.edt_before_19.setObjectName(_fromUtf8("edt_before_19"))
        self.horizontalLayout_19.addWidget(self.edt_before_19)
        self.edi_after_19 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_19.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_19.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_19.setReadOnly(True)
        self.edi_after_19.setObjectName(_fromUtf8("edi_after_19"))
        self.horizontalLayout_19.addWidget(self.edi_after_19)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.field_nm_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_20.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_20.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_20.setFont(font)
        self.field_nm_20.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_20.setObjectName(_fromUtf8("field_nm_20"))
        self.horizontalLayout_20.addWidget(self.field_nm_20)
        self.edt_before_20 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_20.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_20.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_20.setReadOnly(True)
        self.edt_before_20.setObjectName(_fromUtf8("edt_before_20"))
        self.horizontalLayout_20.addWidget(self.edt_before_20)
        self.edi_after_20 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_20.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_20.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_20.setReadOnly(True)
        self.edi_after_20.setObjectName(_fromUtf8("edi_after_20"))
        self.horizontalLayout_20.addWidget(self.edi_after_20)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.field_nm_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_21.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_21.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_21.setFont(font)
        self.field_nm_21.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_21.setObjectName(_fromUtf8("field_nm_21"))
        self.horizontalLayout_22.addWidget(self.field_nm_21)
        self.edt_before_21 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_21.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_21.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_21.setReadOnly(True)
        self.edt_before_21.setObjectName(_fromUtf8("edt_before_21"))
        self.horizontalLayout_22.addWidget(self.edt_before_21)
        self.edi_after_21 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_21.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_21.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_21.setReadOnly(True)
        self.edi_after_21.setObjectName(_fromUtf8("edi_after_21"))
        self.horizontalLayout_22.addWidget(self.edi_after_21)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.field_nm_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_22.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_22.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_22.setFont(font)
        self.field_nm_22.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_22.setObjectName(_fromUtf8("field_nm_22"))
        self.horizontalLayout_23.addWidget(self.field_nm_22)
        self.edt_before_22 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_22.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_22.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_22.setReadOnly(True)
        self.edt_before_22.setObjectName(_fromUtf8("edt_before_22"))
        self.horizontalLayout_23.addWidget(self.edt_before_22)
        self.edi_after_22 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_22.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_22.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_22.setReadOnly(True)
        self.edi_after_22.setObjectName(_fromUtf8("edi_after_22"))
        self.horizontalLayout_23.addWidget(self.edi_after_22)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.field_nm_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_23.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_23.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_23.setFont(font)
        self.field_nm_23.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_23.setObjectName(_fromUtf8("field_nm_23"))
        self.horizontalLayout_24.addWidget(self.field_nm_23)
        self.edt_before_23 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_23.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_23.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_23.setReadOnly(True)
        self.edt_before_23.setObjectName(_fromUtf8("edt_before_23"))
        self.horizontalLayout_24.addWidget(self.edt_before_23)
        self.edi_after_23 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_23.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_23.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_23.setReadOnly(True)
        self.edi_after_23.setObjectName(_fromUtf8("edi_after_23"))
        self.horizontalLayout_24.addWidget(self.edi_after_23)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.field_nm_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_24.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_24.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_24.setFont(font)
        self.field_nm_24.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_24.setObjectName(_fromUtf8("field_nm_24"))
        self.horizontalLayout_25.addWidget(self.field_nm_24)
        self.edt_before_24 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_24.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_24.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_24.setReadOnly(True)
        self.edt_before_24.setObjectName(_fromUtf8("edt_before_24"))
        self.horizontalLayout_25.addWidget(self.edt_before_24)
        self.edi_after_24 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_24.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_24.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_24.setReadOnly(True)
        self.edi_after_24.setObjectName(_fromUtf8("edi_after_24"))
        self.horizontalLayout_25.addWidget(self.edi_after_24)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.field_nm_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.field_nm_25.setMinimumSize(QtCore.QSize(100, 30))
        self.field_nm_25.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.field_nm_25.setFont(font)
        self.field_nm_25.setAlignment(QtCore.Qt.AlignCenter)
        self.field_nm_25.setObjectName(_fromUtf8("field_nm_25"))
        self.horizontalLayout_26.addWidget(self.field_nm_25)
        self.edt_before_25 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edt_before_25.setMinimumSize(QtCore.QSize(130, 30))
        self.edt_before_25.setMaximumSize(QtCore.QSize(130, 30))
        self.edt_before_25.setReadOnly(True)
        self.edt_before_25.setObjectName(_fromUtf8("edt_before_25"))
        self.horizontalLayout_26.addWidget(self.edt_before_25)
        self.edi_after_25 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edi_after_25.setMinimumSize(QtCore.QSize(130, 30))
        self.edi_after_25.setMaximumSize(QtCore.QSize(130, 30))
        self.edi_after_25.setReadOnly(True)
        self.edi_after_25.setObjectName(_fromUtf8("edi_after_25"))
        self.horizontalLayout_26.addWidget(self.edi_after_25)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.btn_ok.setText(_translate("Form", "확 인", None))
        self.label_2.setText(_translate("Form", "Field_name", None))
        self.label.setText(_translate("Form", "Before", None))
        self.label_3.setText(_translate("Form", "After", None))
        self.field_nm_1.setText(_translate("Form", "TextLabel", None))
        self.field_nm_2.setText(_translate("Form", "TextLabel", None))
        self.field_nm_3.setText(_translate("Form", "TextLabel", None))
        self.field_nm_4.setText(_translate("Form", "TextLabel", None))
        self.field_nm_5.setText(_translate("Form", "TextLabel", None))
        self.field_nm_6.setText(_translate("Form", "TextLabel", None))
        self.field_nm_7.setText(_translate("Form", "TextLabel", None))
        self.field_nm_8.setText(_translate("Form", "TextLabel", None))
        self.field_nm_9.setText(_translate("Form", "TextLabel", None))
        self.field_nm_10.setText(_translate("Form", "TextLabel", None))
        self.field_nm_11.setText(_translate("Form", "TextLabel", None))
        self.field_nm_12.setText(_translate("Form", "TextLabel", None))
        self.field_nm_13.setText(_translate("Form", "TextLabel", None))
        self.field_nm_14.setText(_translate("Form", "TextLabel", None))
        self.field_nm_15.setText(_translate("Form", "TextLabel", None))
        self.field_nm_16.setText(_translate("Form", "TextLabel", None))
        self.field_nm_17.setText(_translate("Form", "TextLabel", None))
        self.field_nm_18.setText(_translate("Form", "TextLabel", None))
        self.field_nm_19.setText(_translate("Form", "TextLabel", None))
        self.field_nm_20.setText(_translate("Form", "TextLabel", None))
        self.field_nm_21.setText(_translate("Form", "TextLabel", None))
        self.field_nm_22.setText(_translate("Form", "TextLabel", None))
        self.field_nm_23.setText(_translate("Form", "TextLabel", None))
        self.field_nm_24.setText(_translate("Form", "TextLabel", None))
        self.field_nm_25.setText(_translate("Form", "TextLabel", None))

