# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\extjob.ui'
#
# Created: Sun Apr 24 15:51:04 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(657, 461)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 631, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 611, 62))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.rdo_basetype_map = QtGui.QRadioButton(self.layoutWidget)
        self.rdo_basetype_map.setChecked(True)
        self.rdo_basetype_map.setObjectName(_fromUtf8("rdo_basetype_map"))
        self.horizontalLayout_7.addWidget(self.rdo_basetype_map)
        self.rdo_basetype_photo = QtGui.QRadioButton(self.layoutWidget)
        self.rdo_basetype_photo.setObjectName(_fromUtf8("rdo_basetype_photo"))
        self.horizontalLayout_7.addWidget(self.rdo_basetype_photo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.date_basedata_dt = QtGui.QDateEdit(self.layoutWidget)
        self.date_basedata_dt.setCalendarPopup(True)
        self.date_basedata_dt.setObjectName(_fromUtf8("date_basedata_dt"))
        self.horizontalLayout_7.addWidget(self.date_basedata_dt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.edt_basedata_nm = QtGui.QLineEdit(self.layoutWidget)
        self.edt_basedata_nm.setObjectName(_fromUtf8("edt_basedata_nm"))
        self.horizontalLayout_5.addWidget(self.edt_basedata_nm)
        self.btn_selectfile = QtGui.QPushButton(self.layoutWidget)
        self.btn_selectfile.setObjectName(_fromUtf8("btn_selectfile"))
        self.horizontalLayout_5.addWidget(self.btn_selectfile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 631, 221))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 22, 611, 192))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.cmb_sido = QtGui.QComboBox(self.layoutWidget1)
        self.cmb_sido.setObjectName(_fromUtf8("cmb_sido"))
        self.horizontalLayout.addWidget(self.cmb_sido)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.cmb_sgg = QtGui.QComboBox(self.layoutWidget1)
        self.cmb_sgg.setObjectName(_fromUtf8("cmb_sgg"))
        self.horizontalLayout.addWidget(self.cmb_sgg)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.cmb_emd = QtGui.QComboBox(self.layoutWidget1)
        self.cmb_emd.setObjectName(_fromUtf8("cmb_emd"))
        self.horizontalLayout.addWidget(self.cmb_emd)
        self.btn_add_admin = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_admin.sizePolicy().hasHeightForWidth())
        self.btn_add_admin.setSizePolicy(sizePolicy)
        self.btn_add_admin.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_admin.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_admin.setBaseSize(QtCore.QSize(30, 30))
        self.btn_add_admin.setObjectName(_fromUtf8("btn_add_admin"))
        self.horizontalLayout.addWidget(self.btn_add_admin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.edt_mapbox = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.edt_mapbox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.edt_mapbox.setObjectName(_fromUtf8("edt_mapbox"))
        self.horizontalLayout_4.addWidget(self.edt_mapbox)
        self.btn_add_mapbox = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_mapbox.sizePolicy().hasHeightForWidth())
        self.btn_add_mapbox.setSizePolicy(sizePolicy)
        self.btn_add_mapbox.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_add_mapbox.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_add_mapbox.setBaseSize(QtCore.QSize(30, 30))
        self.btn_add_mapbox.setObjectName(_fromUtf8("btn_add_mapbox"))
        self.horizontalLayout_4.addWidget(self.btn_add_mapbox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lst_workarea = QtGui.QListWidget(self.layoutWidget1)
        self.lst_workarea.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lst_workarea.setObjectName(_fromUtf8("lst_workarea"))
        self.horizontalLayout_6.addWidget(self.lst_workarea)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.btn_gendata = QtGui.QPushButton(Dialog)
        self.btn_gendata.setGeometry(QtCore.QRect(410, 410, 231, 41))
        self.btn_gendata.setObjectName(_fromUtf8("btn_gendata"))
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(12, 18, 631, 23))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.cmb_worker_nm = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_worker_nm.sizePolicy().hasHeightForWidth())
        self.cmb_worker_nm.setSizePolicy(sizePolicy)
        self.cmb_worker_nm.setEditable(True)
        self.cmb_worker_nm.setObjectName(_fromUtf8("cmb_worker_nm"))
        self.horizontalLayout_3.addWidget(self.cmb_worker_nm)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.date_mapext_dttm = QtGui.QDateEdit(self.layoutWidget2)
        self.date_mapext_dttm.setCalendarPopup(True)
        self.date_mapext_dttm.setObjectName(_fromUtf8("date_mapext_dttm"))
        self.horizontalLayout_3.addWidget(self.date_mapext_dttm)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 51, 631, 23))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edt_extjob_nm = QtGui.QLineEdit(self.layoutWidget3)
        self.edt_extjob_nm.setObjectName(_fromUtf8("edt_extjob_nm"))
        self.horizontalLayout_2.addWidget(self.edt_extjob_nm)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "작업용 수치지형도 제공", None))
        self.groupBox.setTitle(_translate("Dialog", "배경자료", None))
        self.rdo_basetype_map.setText(_translate("Dialog", "도면", None))
        self.rdo_basetype_photo.setText(_translate("Dialog", "항공사진", None))
        self.label_10.setText(_translate("Dialog", "배경자료 기준일:", None))
        self.label_4.setText(_translate("Dialog", "자료파일:", None))
        self.btn_selectfile.setText(_translate("Dialog", "선택...", None))
        self.groupBox_2.setTitle(_translate("Dialog", "지형도 제공영역 선택", None))
        self.label_5.setText(_translate("Dialog", "시도:", None))
        self.label_6.setText(_translate("Dialog", "시군구:", None))
        self.label_7.setText(_translate("Dialog", "읍면동:", None))
        self.btn_add_admin.setText(_translate("Dialog", "+", None))
        self.label_8.setText(_translate("Dialog", "도엽:", None))
        self.btn_add_mapbox.setText(_translate("Dialog", "+", None))
        self.label_9.setText(_translate("Dialog", "선택된 영역:", None))
        self.btn_gendata.setText(_translate("Dialog", "작업용 수치지형도 생성", None))
        self.label.setText(_translate("Dialog", "업체명:", None))
        self.label_3.setText(_translate("Dialog", "작업지시일:", None))
        self.label_2.setText(_translate("Dialog", "작업명:", None))

