# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\inspect.ui'
#
# Created: Sun May 15 17:57:04 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(369, 641)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 345, 617))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.cmb_worker_nm = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_worker_nm.sizePolicy().hasHeightForWidth())
        self.cmb_worker_nm.setSizePolicy(sizePolicy)
        self.cmb_worker_nm.setObjectName(_fromUtf8("cmb_worker_nm"))
        self.horizontalLayout_5.addWidget(self.cmb_worker_nm)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.date_mapext_dttm = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.date_mapext_dttm.setCalendarPopup(True)
        self.date_mapext_dttm.setObjectName(_fromUtf8("date_mapext_dttm"))
        self.horizontalLayout_3.addWidget(self.date_mapext_dttm)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmb_extjob_nm = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmb_extjob_nm.setObjectName(_fromUtf8("cmb_extjob_nm"))
        self.horizontalLayout_2.addWidget(self.cmb_extjob_nm)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cmb_receive_id = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmb_receive_id.setObjectName(_fromUtf8("cmb_receive_id"))
        self.horizontalLayout_4.addWidget(self.cmb_receive_id)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.cmb_layer_nm = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmb_layer_nm.setObjectName(_fromUtf8("cmb_layer_nm"))
        self.horizontalLayout_7.addWidget(self.cmb_layer_nm)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.date_basedata_dt = QtGui.QDateEdit(self.scrollAreaWidgetContents)
        self.date_basedata_dt.setReadOnly(True)
        self.date_basedata_dt.setCalendarPopup(False)
        self.date_basedata_dt.setObjectName(_fromUtf8("date_basedata_dt"))
        self.horizontalLayout_6.addWidget(self.date_basedata_dt)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_99 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_99.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_99.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.horizontalLayout_41.addWidget(self.label_99)
        self.edt_inpector = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_inpector.sizePolicy().hasHeightForWidth())
        self.edt_inpector.setSizePolicy(sizePolicy)
        self.edt_inpector.setObjectName(_fromUtf8("edt_inpector"))
        self.horizontalLayout_41.addWidget(self.edt_inpector)
        self.verticalLayout.addLayout(self.horizontalLayout_41)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.btn_start_inspect = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_start_inspect.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_start_inspect.setFont(font)
        self.btn_start_inspect.setObjectName(_fromUtf8("btn_start_inspect"))
        self.gridLayout_2.addWidget(self.btn_start_inspect, 1, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 2, 0, 1, 1)
        self.lbl_progress = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_progress.setObjectName(_fromUtf8("lbl_progress"))
        self.gridLayout_2.addWidget(self.lbl_progress, 3, 0, 1, 1)
        self.btn_accept = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_accept.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_accept.setObjectName(_fromUtf8("btn_accept"))
        self.gridLayout_2.addWidget(self.btn_accept, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_prev = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_prev.setObjectName(_fromUtf8("btn_prev"))
        self.horizontalLayout.addWidget(self.btn_prev)
        self.btn_next = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_next.setObjectName(_fromUtf8("btn_next"))
        self.horizontalLayout.addWidget(self.btn_next)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.btn_reject = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_reject.setObjectName(_fromUtf8("btn_reject"))
        self.gridLayout_2.addWidget(self.btn_reject, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 1)
        self.edt_reject_reason = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.edt_reject_reason.setMinimumSize(QtCore.QSize(0, 100))
        self.edt_reject_reason.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edt_reject_reason.setObjectName(_fromUtf8("edt_reject_reason"))
        self.gridLayout_2.addWidget(self.edt_reject_reason, 8, 0, 1, 1)
        self.btn_make_report = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btn_make_report.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_make_report.setFont(font)
        self.btn_make_report.setObjectName(_fromUtf8("btn_make_report"))
        self.gridLayout_2.addWidget(self.btn_make_report, 9, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "납품 데이터 검수", None))
        self.label.setText(_translate("Dialog", "업체명:", None))
        self.label_3.setText(_translate("Dialog", "작업지시일:", None))
        self.label_2.setText(_translate("Dialog", "작업명:", None))
        self.label_5.setText(_translate("Dialog", "납품 ID:", None))
        self.label_7.setText(_translate("Dialog", "레이어:", None))
        self.label_6.setText(_translate("Dialog", "배경자료기준일:", None))
        self.label_99.setText(_translate("Dialog", "검수자:", None))
        self.btn_start_inspect.setText(_translate("Dialog", "검수 시작", None))
        self.lbl_progress.setText(_translate("Dialog", "변경 탐지중...", None))
        self.btn_accept.setText(_translate("Dialog", "승인", None))
        self.btn_prev.setText(_translate("Dialog", "< 이전항목", None))
        self.btn_next.setText(_translate("Dialog", "다음항목>", None))
        self.btn_reject.setText(_translate("Dialog", "거부", None))
        self.label_4.setText(_translate("Dialog", "거부사유", None))
        self.btn_make_report.setText(_translate("Dialog", "검수 리포트 작성", None))

