# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\receive.ui'
#
# Created: Sun Apr 24 15:51:04 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(660, 382)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.btn_upload = QtGui.QPushButton(Dialog)
        self.btn_upload.setGeometry(QtCore.QRect(420, 280, 231, 41))
        self.btn_upload.setObjectName(_fromUtf8("btn_upload"))
        self.btn_inspect = QtGui.QPushButton(Dialog)
        self.btn_inspect.setGeometry(QtCore.QRect(420, 330, 231, 41))
        self.btn_inspect.setObjectName(_fromUtf8("btn_inspect"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 260, 631, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lbl_progress = QtGui.QLabel(Dialog)
        self.lbl_progress.setGeometry(QtCore.QRect(10, 280, 391, 16))
        self.lbl_progress.setObjectName(_fromUtf8("lbl_progress"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 13, 641, 235))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.cmb_worker_nm = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_worker_nm.sizePolicy().hasHeightForWidth())
        self.cmb_worker_nm.setSizePolicy(sizePolicy)
        self.cmb_worker_nm.setObjectName(_fromUtf8("cmb_worker_nm"))
        self.horizontalLayout_5.addWidget(self.cmb_worker_nm)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.date_mapext_dttm = QtGui.QDateEdit(self.layoutWidget)
        self.date_mapext_dttm.setCalendarPopup(True)
        self.date_mapext_dttm.setObjectName(_fromUtf8("date_mapext_dttm"))
        self.horizontalLayout_3.addWidget(self.date_mapext_dttm)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.date_mapext_dttm_2 = QtGui.QDateEdit(self.layoutWidget)
        self.date_mapext_dttm_2.setCalendarPopup(True)
        self.date_mapext_dttm_2.setObjectName(_fromUtf8("date_mapext_dttm_2"))
        self.horizontalLayout_3.addWidget(self.date_mapext_dttm_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.btn_search = QtGui.QPushButton(self.layoutWidget)
        self.btn_search.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_search.setObjectName(_fromUtf8("btn_search"))
        self.horizontalLayout_6.addWidget(self.btn_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmb_extjob_nm = QtGui.QComboBox(self.layoutWidget)
        self.cmb_extjob_nm.setObjectName(_fromUtf8("cmb_extjob_nm"))
        self.horizontalLayout_2.addWidget(self.cmb_extjob_nm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.lst_workarea = QtGui.QListView(self.layoutWidget)
        self.lst_workarea.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lst_workarea.setObjectName(_fromUtf8("lst_workarea"))
        self.horizontalLayout_4.addWidget(self.lst_workarea)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.edt_data_folder = QtGui.QLineEdit(self.layoutWidget)
        self.edt_data_folder.setObjectName(_fromUtf8("edt_data_folder"))
        self.horizontalLayout.addWidget(self.edt_data_folder)
        self.btn_select_folder = QtGui.QPushButton(self.layoutWidget)
        self.btn_select_folder.setObjectName(_fromUtf8("btn_select_folder"))
        self.horizontalLayout.addWidget(self.btn_select_folder)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "납품 데이터 수령", None))
        self.btn_upload.setText(_translate("Dialog", "납품 데이터 올리기", None))
        self.btn_inspect.setText(_translate("Dialog", "납품 데이터 검수", None))
        self.lbl_progress.setText(_translate("Dialog", "납품 데이터 올리기 준비중...", None))
        self.label.setText(_translate("Dialog", "업체명:", None))
        self.label_3.setText(_translate("Dialog", "작업지시일:", None))
        self.label_5.setText(_translate("Dialog", "~", None))
        self.btn_search.setText(_translate("Dialog", "검색", None))
        self.label_2.setText(_translate("Dialog", "작업명:", None))
        self.label_9.setText(_translate("Dialog", "작업 영역:", None))
        self.label_4.setText(_translate("Dialog", "납품 데이터 폴더:", None))
        self.btn_select_folder.setText(_translate("Dialog", "선택...", None))

